spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${jdbc.url:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${jdbc.username:ol_master}
    password: ${jdbc.password:password12}
    testOnBorrow: true
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 1000
  rabbitmq:
    addresses: localhost:5672
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${port:9060}
  servlet-path: /management

management:
  port: 9160

customer:
  info:
    caller:
      endpoint: http://193.67.163.82/tpicxtmqa/XISOAPAdapter/MessageServlet?senderParty=Online&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=PartyManagementManageCustomer24x7&interfaceNamespace=urn%3Abritishgas.co.uk%3AOnline%3AParty
      expiry: 3600

webservice:
  authentication:
    username: '{cipher}AQCGfQnziqg19aTul0OMHKIb8sR0fRCKQCB96yEE+YkXLOiXhgpOoV7f1GHoEuiXiDjdQ4St45fZYT9XCHio/R9PJQmSRJiiF112kpH3+zwotwTWgRwkc8walfRMzu9x65h6jhruzQWJsBm+juijRHaNttGQUfNJConJ0X7Lbi9ENU7wTDoOcr43RlPYqXvBCD1yxglnT4yjNq674hzvz8MHiyzEKCb5+ADuJHtFn9Jq/KNlTGREGTfSap1cSYSRZY91IoHZzer4j0RF3LJINy8GGbcSBwKSkwm/3crbr6iP9Iz8eNCGe2xYkE8JtWHd0QXvscvgxRbjIuD/B2PHQcJD3SxtQ/BIMGgaUiEZczs7SHak4jkM0rcKPjVcku21y/Q='
    password: '{cipher}AQCQJYTqfmP7HwD0/09qqHxDwYenEnUB7sB9r9nqQGOWYQlUigdqKrn5OaIsKkUmd28rmBbwyN3DmsNL0x9RA9kdZpsOyWgyVgCunJbmiIx2lLbvJmtRfsSx2YadXppwNFxhyYpDvD2VhapvTK00eUwUd0qoxJQSkL30ynJH+JGpORgqhU7frh2Ue/8ns5eScpaBxDPFQTy2gIwO3qhXISi/bUJHO8GPL7Q74qqgMXIZF4vAu+Vca96JLdPsopKUpAihde2WxtccZ53m3wfY+MjuQrCwAKl2kAFWVdKONybdnJBV3Gy79VI/2JP92GNF6t2rRV/fpESWFTgihXsZjlK9qK8vIoqXS8R0fb65K0fdVYE7ssYIEf+zrcimiLVmqxM='

odata:
  host: http://193.67.163.82/tngwntmqa
  authorization: '{cipher}AQBe1Ju9o+yuU15WoWxe9VeNUFnm69fW7sK6dWAZwmpxdi+ieYzyWIX+JYZiIDGM0bObhepMydhGVyEDKVEu1EH/t9UEwO2WB3hxe/W0fQy987MvMPz1tjWdtQ5QIs510VuwPn9SSDOJAYKY5qoAfehI/SJ1yjS2dzqwgADF1+FqRoIYglO0iNwC3EL1ih1VzWB0jG5kPVp7SM3wCfADwXmeTTb2u9GSvzFNsn4zWd+JFNTU08CbgLoN+hUq2whxHxxn0NXnHwJnJU54RKj8lbv267sZhKdLCYXTdzbwLJDPYTK4CnwQd4mRa06IIuPOsAnlja4SMLqhlFuFNjUrydk3eUIGxXsovFV6JhTpH+cWtOxi9vXXtZiluX+hunnevlEe4r0q7jr/pyJK7abli/4N'
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    org.spring: 'INFO'
    org.apache: 'INFO'
    ROOT: 'DEBUG'
    
services:
  addresses: addresses-v1
