spring:
  rabbitmq:
    addresses: localhost:5672
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379

server:
  servlet-path: /management
  error:
    whitelabel:
      enabled: false
  
eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

logging:
  level:
    ROOT: INFO
---
spring:
  profiles: instance-1

server:
  port: ${port:10001}
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
---
spring:
  profiles: instance-2
  
server:
  port: ${port:10002}
  
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:10003}
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
