eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost

accounts:
  test:
    verbiage: accounts-test-verbiage
---
spring:
  profiles: instance-1
    
server:
  port: ${port:56621}

eureka:
  instance:
    metadata-map:
      instanceId: 1    
---
spring:
  profiles: instance-2
    
server:
  port: ${port:56623}
  
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
    
server:
  port: ${port:56725}
  
eureka:
  instance:
    metadata-map:
      instanceId: 3
