 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost

accounts:
  test:
    verbiage: accounts-test-verbiage
---
spring:
  profiles: instance-1
  boot:
    admin:
      url: http://${adminHost:localhost}:${adminPort:56620}
    
server:
  port: ${port:56621}

eureka:
  instance:
    metadata-map:
      instanceId: 1    
---
spring:
  profiles: instance-2
  boot:
    admin:
      url: http://${adminHost:localhost}:${adminPort:56622}
    
    
server:
  port: ${port:56623}
  
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  boot:
    admin:
      url: http://${adminHost:localhost}:${adminPort:56724}
    
server:
  port: ${port:56725}
  
eureka:
  instance:
    metadata-map:
      instanceId: 3
