spring:
  rabbitmq:
    addresses: localhost:5672

memcached:
  addresses: 192.168.99.100:32768

server:
  servlet-path: /management

address:
  lookup:
    parallelism: 15
  
eureka:
  instance:
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'
---
spring:
  profiles: instance-1

server:
  port: ${port:9090}
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
---
spring:
  profiles: instance-2
  
server:
  port: ${port:9091}
  
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:9092}
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
