server:
  port: 9070

spring:
  rabbitmq:
    addresses: ${rabbitmq.host:localhost}:${rabbitmq.port:5672}
    username: guest
    password: guest
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${jdbc.url:jdbc:oracle:thin:@10.224.70.16:1525:DVSOL1_1}
    username: ${jdbc.username:ol_master}
    password: ${jdbc.password:ROLE_MASTER}
    testOnBorrow: true
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 1000
