server:
  port: 9070

spring:
  rabbitmq:
    addresses: ${rabbitmq.host:localhost}:${rabbitmq.port:5672}
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: audits
