server:
  port: 9070

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${jdbc.url:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${jdbc.username:ol_master}
    password: ${jdbc.password:password12}
    testOnBorrow: true
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 1000
  rabbitmq:
    addresses: ${rabbitmq.host:localhost}:${rabbitmq.port:5672}
  cloud:
    stream:
      bindings:
        input:
          destination: audits
        output:
          destination: audits
