eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
customers:
  test:
    verbiage: customers-test-verbiage-reset/updated

---
spring:
  profiles: instance-1
  boot:
    admin:
      url: http://${adminHost:localhost}:${adminPort:56722}
    
server:
  port: ${port:56721}

eureka:
  instance:
    metadata-map:
      instanceId: 1    
---
spring:
  profiles: instance-2
  boot:
    admin:
      url: http://${adminHost:localhost}:${adminPort:56724}
        
server:
  port: ${port:56723}
  
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  boot:
    admin:
      url: http://${adminHost:localhost}:${adminPort:56726}
    
    
server:
  port: ${port:56725}
  
eureka:
  instance:
    metadata-map:
      instanceId: 3
