spring:
  rabbitmq:
    addresses: localhost:5672
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379

memcached:
  addresses: 192.168.99.100:32770

ribbon:
  eureka:
   enabled: false

webservice:
  authentication:
    username: ONLSRVUSER
    password: usatoday1
  personalProjection:
    caller:
      endpoint: http://tpicxtmqa.uk.centricaplc.com:50000/XISOAPAdapter/MessageServlet?senderParty=Online&senderService=BSR_WebService_PI&receiverParty=&receiverService=&interface=QueryProductTariffsOut&interfaceNamespace=urn%3Abritishgas.co.uk%3AEnterprise%3AProduct
      expiry: 3600

cqRepository:
  ribbon:
    listOfServers: 10.224.70.15:9001
    #listOfServers: 10.224.70.74:9001

server:
  port: ${port:9080}
  servlet-path: /management
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    root: INFO
    org.springframework.ws.client.MessageTracing.sent: 'TRACE'
    org.springframework.ws.client.MessageTracing.received: 'TRACE'
