spring:
  rabbitmq:
    addresses: localhost:5672
   
eureka:
  server:
    enableSelfPreservation: false
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: instance-1

server:
  port: ${port:8761}

eureka:
  instance:
    instanceId: 1
    hostname: 10.224.70.49
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  profiles: instance-2

server:
  port: ${port:8762}

eureka:
  instance:
    instanceId: 2
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
