server:
  port: ${port:8761}
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost

spring:
  rabbitmq:
    addresses: 192.168.99.100:32773
