server:
  port: ${port:8761}

management:
  port: ${port:8861}
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    instanceId: 1
    hostname: localhost
    

spring:
  rabbitmq:
    addresses: 192.168.99.100:32770
