server:
  port: ${port:8761}
    
eureka:
  server:
    enableSelfPreservation: false
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost

spring:
  rabbitmq:
    addresses: 192.168.99.100:32770
