spring:
  rabbitmq:
    addresses: 192.168.99.100:32770

redis:
  host: localhost
  port: 6379

ribbon:
  eureka:
   enabled: false
  
cqRepository:
  ribbon:
    listOfServers: 10.224.70.15:9001,10.224.70.74:9001
  
server:
  port: ${port:8083}
  servlet-path: /management
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    com.netflix.discovery: 'INFO'
    org.springframework.cloud: 'DEBUG'
    feign: 'DEBUG'
