redis:
  host: localhost
  port: 6379
  
spring:
  rabbitmq:
    addresses: localhost:5672
  
server:
  port: ${port:8083}
  servlet-path: /management
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
