info:
  component: Turbine
  
spring:
  rabbitmq:
    addresses: localhost:5672
    
turbine:
  clusterNameExpression: 'default'
  appConfig: addresses, zuul

server:
  port: ${port:8111}

management:
  port: ${port:8989}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
