info:
  component: Turbine

spring:
  rabbitmq:
    addresses: 192.168.99.100:32770

turbine:
  clusterNameExpression: 'default'
  appConfig: zuul

server:
  port: ${port:8989}

management:
  port: 8990

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    ROOT: INFO
