info:
  component: Turbine

spring:
  rabbitmq:
    addresses: 192.168.99.100:32770

turbine:
  clusterNameExpression: 'default'
  appConfig: addresses

server:
  port: ${port:8989}

management:
  port: ${port:8990}

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
