info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

spring:
  rabbitmq:
    addresses: 192.168.99.100:32770

turbine:
  clusterNameExpression: 'default'
  appConfig: zuul

server:
  port: ${port:8989}

management:
  port: 8990

logging:
  level:
    root: debug
    com.netflix.discovery: 'OFF'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: cloud
management:
  port: -1
