spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${jdbc.url:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${jdbc.username:ol_master}
    password: ${jdbc.password:password12}
    testOnBorrow: true
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 1000
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

environment: local

endpoints:
  sensitive: false
  trace:
    enabled: false
  shutdown:
    enabled: false
  restart:
    enabled: false

cqServers:
 defaultHost: https://10.114.69.111
 servers:
   ? 'https://10.114.69.15'
   : {
       name: digital-1, 
       hostnames: [ '10.224.70.15', '193.67.163.82', '10.224.70.29' ]
     }
   ? 'https://10.114.69.17'
   : {
       name: digital-2,
       hostnames: [ '10.224.70.17', '193.67.163.83', '10.224.70.19' ]
     }
   ? 'https://10.114.69.18'
   : {
       name: digital-3,
       hostnames: [ '10.224.70.18', '193.67.163.41', '10.224.70.22' ]
     }
   ? 'https://10.114.69.36'
   : {
       name: digital-5,
       hostnames: [ '10.224.70.36', '193.67.163.50', '10.224.70.38' ]
     }
   ? 'https://10.224.69.37'
   : {
       name: digital-6,
       hostnames: [ '10.224.70.37', '193.67.163.39', '10.224.70.41' ]
     }
   ? 'https://10.114.69.44'
   : {
       name: digital-7,
       hostnames: [ '10.224.70.44', '193.67.163.110', '10.224.70.45' ]
     }
   ? 'https://10.114.69.51'
   : {
       name: digital-8,
       hostnames: [ '10.224.70.51', '193.67.163.22', '10.224.70.52' ]
     }
   ? 'https://10.114.69.55'
   : {
       name: digital-9,
       hostnames: [ '10.224.70.55', '10.224.70.56' ]
     }
   ? 'https://10.114.69.59'
   : {
       name: digital-10,
       hostnames: [ '10.224.70.59', '193.67.161.46', '10.224.70.60' ]
     }
   ? 'https://10.114.69.76'
   : {
       name: digital-11,
       hostnames: [ '10.224.70.76', '193.67.164.24', '10.224.70.77' ]
     }
   ? 'https://10.114.69.75'
   : {
       name: digital-12,
       hostnames: [ '10.224.70.75', '193.67.163.21', '10.224.70.80' ]
     }
   ? 'https://10.114.69.83'
   : {
       name: digital-13,
       hostnames: [ '10.224.70.83', '193.67.163.63', '10.224.70.86' ]
     }
   ? 'https://10.114.69.84'
   : {
       name: digital-14,
       hostnames: [ '10.224.70.84', '193.67.161.47', '10.224.70.89' ]
     }
   ? 'https://10.114.69.33'
   : {
       name: digital-15,
       hostnames: [ '10.224.70.33', '193.67.163.51', '10.224.70.34' ]
     }
   ? 'https://10.114.69.95'
   : {
       name: digital-15,
       hostnames: [ '10.224.70.95', '10.224.70.96' ]
     }
   ? 'https://10.114.69.69'
   : {
       name: digital-17,
       hostnames: [ '10.224.70.69', '10.224.70.68' ]
     }
   ? 'https://10.114.69.104'
   : {
       name: digital-18,
       hostnames: [ '10.224.70.104', '193.67.163.23', '10.224.70.105' ]
     }
   ? 'https://10.114.69.111'
   : {
       name: uat-111,
       hostnames: [ '10.224.70.111', '193.67.163.141', '10.224.70.114' ]
     }
   ? 'https://10.114.69.50'
   : {
       name: uat-50,
       hostnames: [ '10.224.70.50', '193.67.160.93', '10.224.70.63' ]
     }
   ? 'https://10.114.69.74'
   : {
       name: prod-74,
       hostnames: [ '10.224.70.74', '193.67.162.139', '10.224.70.108' ]
     }

eureka:
  instance:
    hostname: localhost
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    securePortEnabled: true
    securePort: ${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

encryption:
  AES:
    cbc-iv: ${aes.iv}
    seed: ${aes.seed}

services:
  emails: emails
  audits: audits

logging:
  level:
    ROOT: INFO
    uk.co.britishgas: DEBUG
    com.netflix.discovery: ERROR

server:
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-store: ${ssl.keystore:classpath:keystore.jks}
    key-store-password: ${ssl.key-store-password:password12}
    key-alias: ${ssl.key-alias:localhost}
---
spring:
  profiles: instance-1

server:
  port: 9001

management:
  port: 9006
  ssl:
    enabled: false
---
spring:
  profiles: instance-2

server:
  port: 9002
  
management:
  port: 9007
  ssl:
    enable: false
---
spring:
  profiles: instance-3

server:
  port: 9003

management:
  port: 9008
  ssl:
    enable: false
