spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${jdbc.url:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${jdbc.username:ol_master}
    password: ${jdbc.password:password12}
    testOnBorrow: true
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 1000
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

endpoints:
  sensitive: false
  trace:
    enabled: false
  shutdown:
    enabled: false
  restart:
    enabled: false
  
cqServerUrl: https://localhost:9033
    
eureka:
  instance:
    hostname: localhost
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    securePortEnabled: true
    securePort: ${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

encryption:
  AES:
    cbc-iv: ${aes.iv}
    seed: ${aes.seed}

services:
  emails: emails
  audits: audits

logging:
  level:
    ROOT: INFO
    uk.co.britishgas: DEBUG
    com.netflix.discovery: ERROR

server:
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-store: ${ssl.keystore:classpath:keystore.jks}
    key-store-password: ${ssl.key-store-password:password12}
    key-alias: ${ssl.key-alias:localhost}
---
spring:
  profiles: instance-1

server:
  port: 9001

management:
  port: 9006
  ssl:
    enabled: false
---
spring:
  profiles: instance-2

server:
  port: 9002
  
management:
  port: 9007
  ssl:
    enabled: false
---
spring:
  profiles: instance-3

server:
  port: 9003

management:
  port: 9008
  ssl:
    enabled: false
