info:
  component: Zuul Server
  
zuul:
  ignoredServices: '*'
  routes:
    addresses: 
      path: /addresses/**
spring:
  rabbitmq:
    addresses: localhost:5672
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
---
spring:
  profiles: instance-1

server:
  port: ${port:8771}
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
---
spring:
  profiles: instance-2
  
server:
  port: ${port:8773}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password12
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:8775}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password12
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
