info:
  component: Zuul Server
  
zuul:
  ignoredServices: '*'
  routes:
    addresses: 
      path: /addresses/**
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  rabbitmq:
    addresses: 192.168.99.100:32770
---
spring:
  profiles: instance-1

server:
  port: ${port:8771}
  
eureka:
  instance:
    metadata-map:
      instanceId: 1
---
spring:
  profiles: instance-2
  
server:
  port: ${port:8773}
  
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:8775}
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
