info:
  component: Zuul Server
  
zuul:
  ignoredServices: '*'
  routes:
    addresses-v1:
      path: /v1/addresses/**
      stripPrefix: false
    customers-v1:
      path: /v1/customers/**
      stripPrefix: false

cors:
  mappings:
    /**:
      allowedOrigins:
        - http://www.britishgas.co.uk
        - https://www.britishgas.co.uk
        - http://193.67.163.110
        - https://193.67.163.110
        - chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
      allowedMethods:
        - GET
        - PUT
        - POST
        - PATCH
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Authorization
        - X-Client-ID
        - Content-Type
        - Accept

online:
  ignoredPaths:
    - /**/health
    - /**/info
    - /**/metrics/**
    - /**/refresh
    - /**/restart
    - /**/dump
    - /**/pause
    - /**/bus/**
    - /**/beans
    - /**/mappings
    - /**/env/**
    - /**/resume
    - /**/configprops
    - /**/autoconfig
    - /**/trace
    - /**/features
    - /**/archaius
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  rabbitmq:
    addresses: localhost:5672
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    root: info
---
spring:
  profiles: instance-1

server:
  port: ${port:8771}

management:
  port: 8871
  
eureka:
  instance:
    hostname: 127.0.0.1
    metadata-map:
      instanceId: 1
---
spring:
  profiles: instance-2
  
server:
  port: ${port:8773}

management:
  port: 8873
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:8775}

management:
  port: 8875
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
