info:
  component: Zuul Server
  
zuul:
  stripPrefix: false
  ignoredServices: 'uaa, audits, zuul-server, eureka-server, emails'

cors:
  mappings:
    /*:
      allowedOrigins:
        - www.britishgas.co.uk
        - chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
      allowedMethods:
        - GET
        - POST
        - PATCH
        - DELETE

online:
  ignoredPaths:
    - /**/health
    - /**/info
    - /**/metrics/**
    - /**/refresh
    - /**/restart
    - /**/dump
    - /**/pause
    - /**/bus/**
    - /**/beans
    - /**/mappings
    - /**/env/**
    - /**/resume
    - /**/configprops
    - /**/autoconfig
    - /**/trace
    - /**/features
    - /**/archaius
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

server:
  ssl:
    trust-store: ${ssl.keystore:classpath:ca-localhost.jks}
    trust-store-password: ${ssl.key-store-password:password12}
    
spring:
  rabbitmq:
    addresses: localhost:5672
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
---
spring:
  profiles: instance-1

server:
  port: ${port:8771}

management:
  port: 8871
  
eureka:
  instance:
    hostname: 127.0.0.1
    metadata-map:
      instanceId: 1
---
spring:
  profiles: instance-2
  
server:
  port: ${port:8773}

management:
  port: 8873
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:8775}

management:
  port: 8875
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
