info:
  component: Zuul Server
  
zuul:
  stripPrefix: false
  ignoredServices: '*'
  routes:
    addresses: 
      path: /addresses/**
    tariffs: 
      path: /tariffs/**   
    audits: 
      path: /audits/**
    callbacks: 
      path: /callbacks/**

cors:
  mappings:
    /*:
      allowedOrigins:
        - www.britishgas.co.uk
        - chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
      allowedMethods:
        - GET
        - POST
        - PATCH
        - DELETE

online:
  ignoredPaths:
    - /**/health
    - /**/info
    - /**/metrics/**
    - /**/refresh
    - /**/restart
    - /**/dump
    - /**/pause
    - /**/bus/**
    - /**/beans
    - /**/mappings
    - /**/env/**
    - /**/resume
    - /**/configprops
    - /**/autoconfig
    - /**/trace
    - /**/features
    - /**/archaius
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  rabbitmq:
    addresses: localhost:5672
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

logging:
  level:
    root: INFO
    org.apache.http: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'
---
spring:
  profiles: instance-1

server:
  port: ${port:8771}

management:
  port: 8871
  
eureka:
  instance:
    hostname: 127.0.0.1
    metadata-map:
      instanceId: 1
---
spring:
  profiles: instance-2
  
server:
  port: ${port:8773}

management:
  port: 8873
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:8775}

management:
  port: 8875
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
