info:
  component: Zuul Server
  
proxy:
  auth:
    routes:
      customers: oauth2
      accounts: oauth2

zuul:
  routes:
    accounts: 
      path: /accounts/**
      strip-prefix: true
    customers: 
      path: /customers/**
      strip-prefix: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost

spring:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:8080/user
---
spring:
  profiles: instance-1

server:
  port: ${port:8771}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password12
  
eureka:
  instance:
    metadata-map:
      instanceId: 1

turbine:
  appConfig: customers,accounts
  clusterNameExpression: 'default'
      
---
spring:
  profiles: instance-2
  
server:
  port: ${port:8773}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password12
    
eureka:
  instance:
    metadata-map:
      instanceId: 2
---
spring:
  profiles: instance-3
  
server:
  port: ${port:8775}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password12
    
eureka:
  instance:
    metadata-map:
      instanceId: 3
